# Generated by Django 4.2.7 on 2023-12-05 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
